#!/bin/sh

[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# root privelages not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
        alias $command="doas $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
        cp="cp -iv" \
        mv="mv -iv" \
        rm="rm -vI" \
        bc="bc -ql" \
        mkd="mkdir -pv" \
        yt="youtube-dl --add-metadata -i" \
        yta="yt -x -f bestaudio/best" \
        ffmpeg="ffmpeg -hide_banner" \
        df="df -h" \
        free='free -m' \

# Colorize commands when possible.
alias \
        ls="ls -hN --color=auto --group-directories-first" \
        grep="grep --color=auto" \
        diff="diff --color=auto" \
        ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
        ka="killall" \
        g="git" \
        config="g --git-dir=$HOME/.local/src/dotfiles --work-tree=$HOME" \
        trem="transmission-remote" \
        YT="youtube-viewer" \
        sdn="shutdown -h now" \
        e="$EDITOR" \
        v="$EDITOR" \
        myip='curl ipinfo.io/ip'\
        ports='netstat -tulanp' \
        p="pacman" \
        xi="doas xbps-install" \
        xr="doas xbps-remove -R" \
        xq="xbps-query" \
        z="zathura" \
        sha='shasum -a 256' \
        weather="curl wttr.in" \
        lsa="ls -A" \
        scim=sc-im \

# XDG Compliance
alias \
        vim="vim -u $XDG_CONFIG_HOME/vim/vimrc" \
        brave="brave; rm -r $HOME/.pki/ > /dev/null" \
        abook="abook --datafile $XDG_DATA_HOME/abook/addressbook" \

# Other useful aliases
alias \
        reload='source $XDG_CONFIG_HOME/zsh/.zshrc' \
        updshorts='shortcuts >/dev/null; source $XDG_CONFIG_HOME/shell/shortcutrc; source $XDG_CONFIG_HOME/shell/zshnameddirrc' \
        ref="updshorts; reload" \
        weath="getweather" \

alias clean="lsa | wc -l"


alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
alias ytv-best="youtube-dl -f bestvideo+bestaudio "


if [[ $(uname -a) == *"MANJARO"* ]]; then
true
else
        alias mirror="doas $mirrorcmd -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
        alias mirrord="doas $mirrorcmd --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
        alias mirrors="doas $mirrorcmd --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
        alias mirrora="doas $mirrorcmd --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
fi

