set nocompatible

set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Character mapping for easier navigation
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l

" Make vim look better
syntax on

" Set indent to 8-spaces
set tabstop=8
set shiftwidth=8
set expandtab

" Allow backspacing of everything
set backspace=2

set number relativenumber

set title
set bg=light
set go=a
" set mouse=a
" set nohlsearch
set clipboard+=unnamedplus
set noshowmode
set noruler " disable display of cursor location
set laststatus=0
set noshowcmd

" autocmd BufWritePost * silent !compiler <afile>
inoremap <Space><Space> <Esc>/<++><Enter>"_c4l

inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {}<Esc>i

source $XDG_CONFIG_HOME/vim/plugins/ipa.vim
source $XDG_CONFIG_HOME/vim/plugins/goyo.vim

filetype plugin on

