set nocompatible
"if ! filereadable(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim"'))
	"echo \"Downloading junegunn/vim-plug to manage plugins...\"
	"silent !mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/vim/autoload/
	"silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ${XDG_CONFIG_HOME:-$HOME/.config}/vim/autoload/plug.vim
	"autocmd VimEnter * PlugInstall
"endif

call plug#begin(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/vim/plugged"'))
Plug 'tpope/vim-surround'
call plug#end()

set title
set bg=light
set go=a
set mouse=a
set nohlsearch
set clipboard+=unnamedplus
set noshowmode
set noruler
set laststatus=0
set noshowcmd


set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Character mapping for easier navigation
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l

" Make vim look better
syntax on

" Set indent to 8-spaces
set tabstop=8
set shiftwidth=8
set expandtab

" Allow backspacing of everything
set backspace=2

set number relativenumber

source $XDG_CONFIG_HOME/vim/plugins/ipa.vim
source $XDG_CONFIG_HOME/vim/plugins/goyo.vim

autocmd BufWritePost * silent !compiler <afile>
inoremap <Space><Space> <Esc>/<++><Enter>"_c4l

autocmd FileType html inoremap ;i <em></em><Space><++><Esc>FeT>i
autocmd FileType html inoremap ;p <p></p><Enter><Enter><++><Esc>2ki
autocmd FileType html inoremap ;i <em></em><Space><++><Esc>FeT>i
autocmd FileType html inoremap ;i <em></em><Space><++><Esc>FeT>i
